inherits: Common.yml

dimensions: 
- alias: ext
  values: ["xls", "xlsx", "xlsm", "xlt", "xltx", "xltm", "xlsb", "xlam", "ods", "ots", "fods", "sxc"]

dictionaries: ["..\\data\\SpreadsheetFamilyDict_{lang}.json"]

outputPath: "{product}\\{ext}.{lang}.md"