inherits: Common.yml

dimensions: 
- alias: ext
  values: ["doc", "docm", "docx", "dot", "dotm", "dotx", "rtf", "odt", "ott"]

dictionaries: ["..\\data\\WordProcessingFamilyDict_{lang}.json"]

outputPath: "{product}\\{ext}.{lang}.md"