inherits: Common.yml

dimensions: 
- alias: ext
  values: ["doc", "docx", "docm", "dot", "dotx", "dotm", "rtf", "odt", "ott"]

dictionaries: ["..\\data\\WordProcessingFamilyDict_{lang}.json"]

outputPath: "{product}\\{ext}.{lang}.md"