TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\AllFormatsDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\DelimitedTextFamilyDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\EbookFamilyDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\EmailFamilyDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\FixedLayoutFamilyDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\PresentationFamilyDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\SpreadsheetFamilyDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\TextualFamilyDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\WordProcessingFamilyDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\single\IndexRootDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\single\IndexNetDict_en.json -d no,ro,sv,ur --overwrite
TranslationTools\net6.0\Res.Translator.exe -s en -r ..\data\single\IndexJavaDict_en.json -d no,ro,sv,ur --overwrite